CXX ?= clang++
MACSDK=$(shell xcrun --show-sdk-path --sdk macosx)
CXXFLAGS=-arch arm64 -fPIC -shared -D__PLUGIN__ -Wall -Wextra -std=c++17 -isysroot $(MACSDK) -DUSE_DANGEROUS_FUNCTIONS=1 -DUSE_STANDARD_FILE_FUNCTIONS=1 -D__MAC__=1
LDFLAGS=-shared -arch arm64
LIBS=-lc -lpthread -ldl
INCLUDES=-I$(IDA_SDK)/include

SRCDIR=./
SRC=$(SRCDIR)CodeXplorer.cpp \
    $(SRCDIR)Compat.cpp \
    $(SRCDIR)CtreeExtractor.cpp \
    $(SRCDIR)CtreeGraphBuilder.cpp \
    $(SRCDIR)Debug.cpp \
    $(SRCDIR)GCCObjectFormatParser.cpp \
    $(SRCDIR)GCCTypeInfo.cpp \
    $(SRCDIR)GCCVtableInfo.cpp \
    $(SRCDIR)IObjectFormatParser.cpp \
    $(SRCDIR)IntegratedTreeExplorer.cpp \
    $(SRCDIR)ModernObjectExplorer.cpp \
    $(SRCDIR)MSVCObjectFormatParser.cpp \
    $(SRCDIR)ObjectExplorer.cpp \
    $(SRCDIR)ReconstructableType.cpp \
    $(SRCDIR)reconstructed_place_t.cpp \
    $(SRCDIR)TreeVTableExplorer.cpp \
    $(SRCDIR)TypeExtractor.cpp \
    $(SRCDIR)TypeReconstructor.cpp \
    $(SRCDIR)UnifiedObjectExplorer.cpp \
    $(SRCDIR)MicrocodeExtractor.cpp \
    $(SRCDIR)Utility.cpp

#SRC = $(wildcard src/*.cpp)
#OBJS=$(subst .cpp,.o,$(SRC))

all: check-env HexRaysCodeXplorer.dylib

HexRaysCodeXplorer.dylib: $(SRC)
	$(CXX) $(LDFLAGS) $(SRC) $(CXXFLAGS) -L$(IDA_SDK)/lib/arm64_mac_clang_64 $(INCLUDES) -D__EA64__=1 $(LIBS) -lida -o HexRaysCodeXplorer.dylib

clean:
	rm -f HexRaysCodeXplorer.dylib
	rm -f libpro.a

install:
	cp -f HexRaysCodeXplorer.dylib $(IDA_DIR)/plugins/

check-env:
ifndef IDA_SDK
    $(error IDA_SDK is undefined)
endif

.PHONY: check-env
